// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_RV_DM__REGS       = 32'h 00040000;
  localparam logic [31:0] ADDR_SPACE_RV_DM__MEM        = 32'h 00030000;
  localparam logic [31:0] ADDR_SPACE_RV_PLIC           = 32'h 08000000;
  localparam logic [31:0] ADDR_SPACE_RV_CORE_IBEX__CFG = 32'h 00010000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER          = 32'h 00020000;
  localparam logic [0:0][31:0] ADDR_SPACE_PERI              = {
    32'h 80000000
  };

  localparam logic [31:0] ADDR_MASK_RV_DM__REGS       = 32'h 00000003;
  localparam logic [31:0] ADDR_MASK_RV_DM__MEM        = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_PLIC           = 32'h 07ffffff;
  localparam logic [31:0] ADDR_MASK_RV_CORE_IBEX__CFG = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER          = 32'h 000001ff;
  localparam logic [0:0][31:0] ADDR_MASK_PERI              = {
    32'h 7fffffff
  };

  localparam int N_HOST   = 3;
  localparam int N_DEVICE = 6;

  typedef enum int {
    TlRvDmRegs = 0,
    TlRvDmMem = 1,
    TlRvPlic = 2,
    TlRvCoreIbexCfg = 3,
    TlRvTimer = 4,
    TlPeri = 5
  } tl_device_e;

  typedef enum int {
    TlRvCoreIbexCorei = 0,
    TlRvCoreIbexCored = 1,
    TlRvDmSba = 2
  } tl_host_e;

endpackage
