// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h00040000, 32'h00040003}
    }},
    '{"rv_dm__mem", '{
        '{32'h00030000, 32'h00030fff}
    }},
    '{"rv_plic", '{
        '{32'h08000000, 32'h0fffffff}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h00010000, 32'h000100ff}
    }},
    '{"rv_timer", '{
        '{32'h00020000, 32'h000201ff}
    }},
    '{"peri", '{
        '{32'h80000000, 32'hffffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rv_dm__mem",
        "peri"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "rv_plic",
        "rv_core_ibex__cfg",
        "rv_timer",
        "peri"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rv_dm__mem",
        "rv_dm__regs",
        "rv_plic",
        "rv_core_ibex__cfg",
        "rv_timer",
        "peri"}}
};
